
"""
Author: Mohammad Dehghani Ashkezari <mdehghan@uw.edu>

Holds cross-project settings and constants.
"""
import os


########### project directories ###########
HOME = f"{os.path.realpath(os.path.dirname(__file__))}/../untrack/"
DATA_DIR = f"{HOME}data/"                                    # where data files (observations of cyanobacteria) are stored.
RAW_DATA_DIR = f"{DATA_DIR}raw/"                             # where data files (observations of cyanobacteria) are stored.
COLOCALIZED_DIR = f"{DATA_DIR}augmented/"                    # where the colocalized data files (with evironmental variables) are stored.
COMPILED_DIR = f"{DATA_DIR}compiled/"                        # where the compiled colocalized data files are stored.
EXPLORE_DIR = f"{HOME}explore/"                              # where the results (data or figure files) of early data explorations are stored.
MAN_DIR = f"{HOME}man/"                                      # where the manuscript figures are stored.
FIGURE_DIR = f"{HOME}figure/"                                # where the analysis figures are stored.
PRODUCTION_DIR = f"{HOME}prod/"                              # where the trained ML models are stored.
MODEL_TEST_DIR = f"{HOME}model_test/"                        # where the model test results are stored.
SPATIAL_PRED_DIR = f"{HOME}spatial_pred/"                    # where the model spatial predictions are stored.
SPATIAL_PRED_DATA_DIR = f"{SPATIAL_PRED_DIR}data/"           # where the model spatial prediction data files are stored.
SPATIAL_PRED_FIG_DIR = f"{SPATIAL_PRED_DIR}fig/"             # where the model spatial prediction figures are stored.
VID_DIR = f"{HOME}video/"                                    # where the videos generated by the ML model spatial predictions are stored.

#################### data retieval settings ####################
DEPTH1 = 0            # The lower bound of vertical filter to retrieve the Cyanobacteria observations.
DEPTH2 = 1e5          # The upper bound of vertical filter to retrieve the Cyanobacteria observations.
SURFACE_DEPTH = 10

########### consistent names for Cyanobacteria studied in the project ###########
PROC = "prochlorococcus_abundance"                      # A consistent label for all "prochlorococcus abundance" related observations.
SYNC = "synechococcus_abundance"                        # A consistent label for all "synechococcus_ abundance" related observations.
PICO = "picoeukaryote_abundance"                        # A consistent label for all "picoeukaryote abundance" related observations.                    
HETB = "heterotrophic_bacteria_abundance"               # A consistent label for all "heterotrophic bacteria abundance" related observations.                    
TARGETS = [PROC, SYNC, PICO, HETB]

#################### Machine Learning ####################
N_JOBS = -1
EPOCHS = 200
VERBOSE_FIT = 1
VALIDATION_SPLIT = 0.1


layers = [
          {"type": "dense", "units": 256, "activation": "relu"},
          {"type": "dropout", "drop": 0.2},
          {"type": "dense", "units": 256, "activation": "relu"},
          {"type": "dropout", "drop": 0.2},
          {"type": "dense", "units": 256, "activation": "relu"},
          {"type": "dropout", "drop": 0.2},
          {"type": "dense", "units": 256, "activation": "relu"},
          {"type": "dropout", "drop": 0.2}
         ]

DEFAULT_NN_HYPER_PARAMS = {"features": None,
                           "layers": layers,
                           "epoch": 500,
                           "batch": 64,
                           "learning": 0.001,
                           "optimizer": "Adam",
                           "loss": "mse"
                           }
